{{- if not .Values.mongodb.uri }}
{{- if .Values.mongodb.secretProviderClass }}
# CSI Driver will handle the secret mounting
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.secretName }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.mongodb.secretKey }}: {{ .Values.mongodb.secret | b64enc | quote }}
{{- end }}
{{- end }} 