service: ins-webserver

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    API_GATEWAY_URL: ${self:custom.apiGatewayUrl.${self:provider.stage}}

custom:
  apiGatewayUrl:
    dev: https://dev-api.insecurazon.local
    staging: https://staging-api.insecurazon.local
    prod: https://api.insecurazon.local

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

package:
  individually: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - 'dist/**'
    - 'node_modules/**'
    - '!src/**'
    - '!test/**'
    - '!**/*.ts'

plugins:
  - serverless-offline 