version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=insecurazon
    networks:
      - backend-network

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017/insecurazon
    depends_on:
      - mongodb
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb_data: 