replicaCount: 1

image:
  repository: insecurazon/product-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

deployment:
  containerPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  path: /health/live
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /health/ready
  initialDelaySeconds: 5
  periodSeconds: 5

mongodb:
  uri: mongodb://mongo:27017/insecurazon
  # For production, use secretRef instead of uri
  secretName: mongodb-secret
  secretKey: mongodb-uri

environment:
  - name: PORT
    value: "8080" 