name: Deploy Infrastructure Pipeline

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [infrastructure-master]
  workflow_dispatch:
    inputs:
      deploy_infra:
        description: 'Deploy infrastructure'
        required: false
        type: boolean
        default: false

env:
  TF_STATE_BUCKET: insecurazon-terraform-state-bucket
  AWS_REGION: eu-central-1
  DEPLOYMENT_ROLE_ARN: arn:aws:iam::767398092878:role/GitHubActions-DeploymentRole

jobs:
  # Job 1: Deploy Infrastructure
  deploy-infrastructure:
    runs-on: ubuntu-24.04
    # Only run this job if explicitly triggered via workflow_dispatch with deploy_infra=true
    # if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_infra == 'true'
    
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init & Apply
        run: |
          cd deploy/infrastructure
          terraform init -backend-config="bucket=${TF_STATE_BUCKET}"
          terraform apply -auto-approve
          